backend:
  name: git-gateway
  identity_url: "https://mt-conservation-district-map.netlify.app/.netlify/identity"
  gateway_url: "https://mt-conservation-district-map.netlify.app/.netlify/git/github"
  repo: MontanaConservationDistricts/conservation-district-map
  branch: master # Branch to update (optional; defaults to master)
  # open_authoring: true
  
# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under images/uploads
logo_url: "/static/site-branding/MACD-Logo_Rect_Blue.png"

collections:
  # Our pages e.g. About
  - label: "Settings"
    name: "settings"
    files:
    - label: "General Settings"
      name: "general"
      file: "_data/settings.json"
      extension: "json"
      description: "General Site Settings"
      fields:
        - {label: "Site Title", name: "siteTitle", widget: "string", required: true, default: "Conservation District Map" }
        - label: "Site Styling"
          name: "siteStyling"
          widget: "object"
          fields:
            - { label: 'Primary Color Override', name: 'primaryColorOverride', widget: 'color', allowInput: true, required: false }
            - { label: 'Secondary Color Override', name: 'secondaryColorOverride', widget: 'color', allowInput: true, required: false }
    - label: "Site Metadata"
      name: "metadata"
      file: "_data/metadata.json"
      extension: "json"
      description: "Metadata for the site"
      fields:
        - {label: "Metadata Title", name: "title", widget: "string", required: true, default: "Montana Conservation District Map"}
        - {label: "Metadata Description", name: "description", widget: "string",required: true, default: "A map for learning about Montana's Conservation Districts."}
        - {label: "URL", name: "url", widget: "hidden", default: "/"}
    - label: "Map Settings"
      name: "map"
      file: "_data/settingsMap.json"
      extension: "json"
      description: "Map Settings"
      fields:
        - {label: "Conservation District GeoJSON Data File", name: "geojson", widget: "file", media_folder: '/static/geospatial',default: "district-boundaries_simplified.geojson", multiple: false}
        - {label: "Default Map Center", name: "center", widget: "map", required: false }
        - {label: "Default Zoom", name: "zoom", widget: "number", required: false, min: 1, max: 20, default: 6.5 }
        - label: "Layer Options"
          name: "layers"
          widget: "object"
          collapsed: false
          fields:
            - label: "Texture Layer"
              name: "texture"
              widget: "object"
              collapsed: true
              fields:
                - {label: "Texture Layer", name: "textureAdd", widget: "boolean", default: true}
                - {label: "Texture File", name: "textureFile", widget: "file", media_folder: '/static/geospatial',default: "/static/geospatial/paper-1.png", multiple: false}
            - label: "Basemap Layers"
              name: "basemaps"
              widget: "list"
              summary: 'Layer - {{fields.presets}} - {{fields.targetPane}}'
              fields:
                - label: "Basemap Presets"
                  name: "presets"
                  widget: "select"
                  options: 
                    - {label: "Mapbox - Conservation Districts Basemap", value: "mapbox basemap"}
                    - {label: "Mapbox - Conservation Districts Labels", value: "mapbox labels"}
                    - {label: "Open Street Map - Default", value: "osm"}
                    - {label: "Custom", value: "custom"}

                - label: "Custom Basemap"
                  description: "Enter the url string to add a custom basemap option. This overrides any of the preset basemaps in the option above."
                  name: "customBasemap"
                  widget: "object"
                  collapsed: true
                  fields:
                    - {label: "Enable Custom Layer", name: "enabled", widget: "boolean", default: false}
                    - {label: "URL", name: "url", widget: "string", default: "https://...", required: true}
                - label: "Target Pane"
                  name: "targetPane"
                  widget: "select"
                  options: 
                    - {label: "Top", value: "top"}
                    - {label: "Bottom", value: "basemap"}

# Our blog posts
  - name: "stories" # Used in routes, e.g., /admin/collections/blog
    label: "Stories" # Used in the UI
    folder: "stories" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Story Title", name: "title", widget: "string" , required: true}
      - { label: "Slug", name: "slug", widget: "string" , required: true}
      - { label: "Publish Date", name: "date", widget: "datetime", required: true }
      - { label: "Author", name: "author", widget: "string", default: "Anonymous", required: false }
      - { label: "Summary", name: "summary", widget: "markdown", required: false}
      - label: "Featured Image"
        name: "featuredImage"
        widget: "image"
        media_folder: "/static/img"
        choose_url: true
        required: false
        media_library:
          config:
            multiple: false
      - {label: "Story Marker", name: "location", widget: "map", required: false }
      - label: "Style"
        name: "style"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Popup Width", name: "width", widget: "string", required: false }
          - { label: 'Story Primary Color', name: 'primaryColor', widget: 'color', allowInput: true, required: false }
          - { label: 'Story Secondary Color', name: 'secondaryColor', widget: 'color', allowInput: true, required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  # Our blog posts
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "District" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Conservation District", name: "title", widget: "string" , required: true, placeholder: "Montana County"}
      - { label: "CD Name Short", name: "titleShort", widget: "string" , required: true, placeholder: "Montana County"}
      - { label: "Publish Date", name: "date", widget: "datetime", required: true }
      - { label: "Author", name: "author", widget: "string", default: "Anonymous", required: false }
      - { label: "Summary", name: "summary", widget: "markdown", required: false}
      - label: "Logo"
        name: "logo"
        widget: "image"
        media_folder: "/static/img"
        choose_url: true
        required: false
        media_library:
          config:
            multiple: false
      - label: "Style"
        name: "style"
        widget: "object"
        collapsed: true
        fields:
          - label: "Popup Area"
            name: "area"
            widget: "select"
            options:
              - { label: "Justify Right", value: "right" }
              - { label: "Justify Left", value: "left" }
              - { label: "Hidden", value: "hidden" }
            default:              
              - { label: "Justify Right", value: "right" }
          - { label: "Popup Width", name: "width", widget: "string", required: false }
          - { label: 'Organization Primary Color', name: 'primaryColor', widget: 'color', allowInput: true, required: false }
          - { label: 'Organization Secondary Color', name: 'secondaryColor', widget: 'color', allowInput: true, required: false }
      - label: "Contact"
        name: "contact"
        widget: "object"
        collapsed: true
        fields:
          - {label: "Website", name: "website", widget: "string", required: false, hint: "https://..."}
          - {label: "Email", name: "primaryEmail", widget: "string",required: false}
          - {label: "Phone", name: "primaryPhone", widget: "string",required: false}
          - label: "Social Media"
            name: "social"
            widget: "list"
            summary: '{{fields.socialItem}} - {{fields.socialItemUrl}}'
            fields:
              - label: "Social Item"
                name: "socialItem"
                widget: "select"
                options: 
                  - {label: "Facebook", value: "facebook", hint: "https://..." }
                  - {label: "Instagram", value: "instagram", hint: "https://..." }
                  - {label: "Twitter", value: "twitter", hint: "https://..."}
                  - {label: "Newsletter", value: "newsletter", hint: "https://..."}
                  - {label: "Other", value: "other", hint: "https://..."}
              - {label: "Link", name: "socialItemUrl", widget: "string", default: "", required: true }
      - label: "Locations"
        name: "locations"
        widget: "list"
        collapsed: true
        summary: '{{fields.addressLabel}}'
        fields:
            - {label: "Label", name: "addressLabel", widget: "string",required: false}
            - {label: "Address Line 1", name: "addressLine1", widget: "string",required: false}
            - {label: "Address Line 2", name: "addressLine2", widget: "string",required: false}
            - {label: "City", name: "city", widget: "string",required: false}
            - {label: "State", name: "state", widget: "string", default: "MT", required: false}
            - {label: "Postal Code", name: "post-code", widget: "string",required: false}
            - {label: "Hours for Address", name: "hours", widget: "string",required: false}    
      - { label: "Tags", name: "tags", widget: "list", default: [""],required: true }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Geospatial ID", name: "id", widget: "string", required: true } 
      

  # Our pages e.g. About
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: false # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Body", name: "body", widget: "markdown" }



