backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under images/uploads

collections:
  # Our blog posts
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "District" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Anonymous" }
      - { label: "Summary", name: "summary", widget: "text" }
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        media_folder: "/static/img"
        choose_url: true
        media_library:
          config:
            multiple: false
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Geospatial ID", name: "id", widget: "string" } 
      - label: "Contact"
        name: "contact"
        widget: "object"
        collapsed: false
        fields:
          - {label: "Website", name: "website", widget: "string", required: false}
          - label: "Social Media"
            name: "social"
            widget: "object"
            collapsed: true
            fields: 
              - {label: "Facebook", name: "facebook", widget: "string",required: false}
              - {label: "Instagram", name: "instagram", widget: "string",required: false}
              - {label: "Twitter", name: "twitter", widget: "string",required: false}
              - {label: "Newsletter", name: "newsletter", widget: "string",required: false}
              - {label: "Other", name: "other", widget: "string",required: false}
          - label: "Employee Contact"
            name: "employee-name"
            widget: "object"
            collapsed: true
            fields: 
              - {label: "Public", name: "public", widget: "boolean", default: true}
              - {label: "Employee Name", name: "employeeName", widget: "string",required: false}
              - {label: "Position", name: "employeePosition", widget: "string",required: false}
              - {label: "Email", name: "employeeEmail", widget: "string",required: false}
              - {label: "Phone", name: "employeePhone", widget: "string",required: false}
          - label: "Office Address"
            name: "address"
            widget: "object"
            collapsed: true
            fields: 
              - {label: "Street Address", name: "street", widget: "string"}
              - {label: "City", name: "city", widget: "string"}
              - {label: "Postal Code", name: "post-code", widget: "string"}

  # Our pages e.g. About
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: false # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Body", name: "body", widget: "markdown" }